---
test:
  name: smallbank
  description: This is smallbank benchmark for caliper
  clients:
    type: local
    number: 10
  rounds:
  - label: smallOperations
    txNumber:
    - 40000
    rateControl:
    - type: fixed-rate
      opts:
        tps: 1000
    arguments:
      accounts: 40000
      txnPerBatch: 10
    callback: benchmarks/scenario/smallbank/smallbankOperations.js
monitor:
  type: docker
  docker:
    name:
    - all
  interval: 1
